language: go
go:
- '1.11'
install: true
before_script: export GO111MODULE=on
script: make build
addons:
  ssh_known_hosts:
  - "$HOST"
after_success:
- rsync -av -e "ssh -o StrictHostKeyChecking=no" output/linux/* home@$HOST:/home/home/test
notifications:
  email:
    recipients:
    - cn100800@163.com
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_859b60f93fdb_key -iv $encrypted_859b60f93fdb_iv
  -in cn.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
env:
  global:
    secure: esuN29TNE7ihUYJqBD4V2ZDMzuObLJhSZT4FuKbi3AD63CYdk484fe61S+Xevb+X92szSJgP8rI78UrSY3guLHoljO65t9Zf6uSyofwtcxnBpFNpHiAxwBVKZ7glI0FM5DxrlZdOSFdo9Q3zoG6PY/XPgRB1NkHUpJLvavPfCljacWGOIU7yKqQIi77B2kwnQuecJsAXshlM7hnFP2FJDIbttxL6aoy2IgHuoPZA2DJ5C+oT6MisTnDzOzJy2oxjUkJVAhBNsH6BnKsbDrEU7HOWypLbzhDs5wq1NCRdB5tTvjDUEcsALHHnIFBBXYpVya9CaGMFrdyYBwss5bPSnvGjivmQ/w7qKLttwXpMGBo6cAlfBB4JnrF/LPm8Vzv3L4J/2RN3v8dGEfjSLQF7KeVkHRlmuTpH85jz5D9JwG6axesDk21S/Ha6wL/EnFD95cJLKY5r1+1R9PbL/Bf4HOgzIAU23KRRk2SjX5RrZuVPdJsbsdNgLXiWDFvaCy83guzkyscEaQ3qb5PNpwkBjVaxJmzI6bt94NhkqjpmtFCV9H9rlSVi7Xc1+2AJJwTcjVV/+I/07i3SYbXajpGT2OVz4xYLQ5Zw9AE/ID/8GXCHtJCCHMoWcnnnVxgEydXpxFuZPfQhRwizfBODQuzuA7RzHpJjBCqWtpS2tQMCrtU=
deploy:
  provider: releases
  file_glob: true
  file:
  - release/*
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: oUebuPK8POIZF6xFlil0WX2b3tbM5zbJVIPLfQWJhq3LT4mn70ArLvE5Pu8wQpyNkqa9ocs/W9RRbY7CI+ZiWC+fGFv6UEGlejb3pHEae/EhGcU5Y3fgtNXFi2CP3ekagsiQgkZAjAX+MdyN7ET6p7PHrDlQfRsn6o+UAM9OoEVpv2heAsWY03+rd/SNa2njorLo93jXrKgLybTnk4Bwexh3ocf+x4powuwogLZkoYgD0fXeJGEP/dV3ln1vbxv3hbMQSZdeoNu8Nx8gMZAF7oW2rP54yETdm9qDdltKsadbrgXiWjutYbPBKmV0hkoANDrCVozKTJFrEuvlaIcbF8fp++B3N1JdMJDu4A9mBkUEU/+CaOIsP0iGRvV9ZWwC7J1Z6cys5GTkzUI/kh1O5DPsH4CXh2p4fSnP73L6vWcxLbZCZNYoRV2UuafyWQfJNkKWXGS0G7fCF5VEax/LcRgVM25WVm/LRSA+29uXIIQ9O7P5OtubKiSzCa/AkMQ1kQDQsb1vL3dz+L88R9krx5BX4cht8JrbAY/rKgJFjVGrh6liU5JiFPLDR/QsSC4oFrbeYqvodGvaqV+BaFoJeBSDysooVhoU9pWKmqQmu6xeajWazPJqVBCWXYGRg8i0NSsTJvJYxiWBRtwWQctR81s1Jf8YY/YFNFPPIR/OjSc=
